CREATE TABLE Lead (
	ID int,
	firstname varchar(255) DEFAULT NULL,
	lastname varchar(255) DEFAULT NULL,
	company varchar(255) DEFAULT NULL,
	phone varchar(255) DEFAULT NULL,	
	leadSource varchar(255) DEFAULT NULL,
	annualRevenue int,
	industry varchar(255) DEFAULT NULL,	
	city varchar(255) DEFAULT NULL,
	country varchar(255) DEFAULT NULL,
	postalCode varchar(255) DEFAULT NULL,
	state varchar(255) DEFAULT NULL,
	street varchar(255) DEFAULT NULL,
	website varchar(255) DEFAULT NULL,
	email varchar(255) DEFAULT NULL,
	fax varchar(255) DEFAULT NULL,	
	description varchar(2000) DEFAULT NULL,
	status varchar(255) DEFAULT NULL,
	createdDate timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	lastModifiedDate timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	lastModifiedById varchar(255) NOT NULL DEFAULT 'mule@localhost',
	PRIMARY KEY (ID)
);